apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
  namespace: stock-tracker
  labels:
    app: express-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
        - name: express-backend
          image: goodmanisltd/stock-tracker-express-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: express-backend-secrets
                  key: MONGO_URI
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: express-backend-secrets
                  key: MONGO_DB
---
apiVersion: v1
kind: Service
metadata:
  name: express-backend-service
  namespace: stock-tracker
  labels:
    app: express-backend
spec:
  type: ClusterIP
  selector:
    app: express-backend
  ports:
    - name: http
      port: 3001
      targetPort: 3001
