apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stock-tracker
resources:
  - namespace.yaml
  - expo_api_backend_depl.yaml
# images:
#   - name: DOCKERHUB_USERNAME/stock-tracker-express-backend
#     newTag: latest
