apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-tracker-ingress
  namespace: stock-tracker
  annotations:
spec:
  ingressClassName: traefik
  rules:
    - host: stock-tracker-api.goodmanltd.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: express-backend-service
                port:
                  number: 3001
    - host: live-tracker.goodmanltd.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: live-tracker-service
                port:
                  number: 8080